version: "3.9"

services:

  postgres:
    restart: always
    image: postgres
    container_name: postgres_default
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hydroponicsystem
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres_data:/var/lib/pgsql/data
