version: "3.9"

services:

  postgres:
    restart: always
    image: postgres
    container_name: postgres_default
    environment:
      - POSTGRES_USER=postgresc
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hydroponicsystem
      - POSTGRES_PORT=c
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres_data:/var/lib/pgsql/data

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin4_defaultc
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    depends_on:
      - postgres
    ports:
      - "5051:80"